-- MySQL Script generated by MySQL Workbench
-- Thu Aug  5 13:55:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema text_mined_assertions
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema text_mined_assertions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `text_mined_assertions` DEFAULT CHARACTER SET utf8 ;
USE `text_mined_assertions` ;

-- -----------------------------------------------------
-- Table `text_mined_assertions`.`assertion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `text_mined_assertions`.`assertion` ;

CREATE TABLE IF NOT EXISTS `text_mined_assertions`.`assertion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assertion_id` VARCHAR(65) NOT NULL,
  `subject_curie` VARCHAR(100) NOT NULL,
  `object_curie` VARCHAR(100) NOT NULL,
  `association_curie` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `assertion_id`),
  INDEX `id_index` (`id` ASC) VISIBLE,
  UNIQUE INDEX `assertion_id_index` (`assertion_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `text_mined_assertions`.`evidence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `text_mined_assertions`.`evidence` ;

CREATE TABLE IF NOT EXISTS `text_mined_assertions`.`evidence` (
  `evidence_id` VARCHAR(65) NOT NULL,
  `assertion_id` VARCHAR(65) NOT NULL,
  `document_id` VARCHAR(45) NOT NULL,
  `sentence` VARCHAR(2000) NOT NULL,
  `subject_entity_id` VARCHAR(65) NOT NULL,
  `object_entity_id` VARCHAR(65) NOT NULL,
  `document_zone` VARCHAR(45) NOT NULL,
  `document_publication_type` VARCHAR(100) NOT NULL,
  `document_year_published` YEAR NOT NULL,
  PRIMARY KEY (`evidence_id`),
  INDEX `assertion_id_idx` (`assertion_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `text_mined_assertions`.`entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `text_mined_assertions`.`entity` ;

CREATE TABLE IF NOT EXISTS `text_mined_assertions`.`entity` (
  `entity_id` VARCHAR(65) NOT NULL,
  `span` VARCHAR(45) NOT NULL,
  `covered_text` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`entity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `text_mined_assertions`.`evidence_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `text_mined_assertions`.`evidence_score` ;

CREATE TABLE IF NOT EXISTS `text_mined_assertions`.`evidence_score` (
  `evidence_id` VARCHAR(65) NOT NULL,
  `predicate_curie` VARCHAR(100) NOT NULL,
  `score` DECIMAL(10,9) NOT NULL,
  UNIQUE INDEX `evidence+predicate` (`evidence_id` ASC, `predicate_curie` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
