#!/bin/sh

source ./rrun.env.sh

SCRIPT=./scripts/pipelines/concepts/run_post_process.sh

TEXT_PIPELINE_KEY=MEDLINE_XML_TO_TEXT
TEXT_PIPELINE_VERSION="0.1.1"
MAX_SUBSET_INDEX=36
SUBSET_PREFIX=PUBMED_SUB_

AUGMENTED_TEXT_PIPELINE_KEY="DOC_TEXT_AUGMENTATION"
AUGMENTED_TEXT_PIPELINE_VERSION="recent"
OGER_PP_PIPELINE_VERSION="recent"
ABBREV_PIPELINE_VERSION="recent"
CRF_PIPELINE_VERSION="recent"

OUTPUT_PIPELINE_VERSION='0.3.0'

#FILTER_FLAG=NONE
FILTER_FLAG=BY_CRF


# # ---------------------------------------------
# # process a single collection
# COLLECTION="PUBMED_SUB_37"
# $SCRIPT $PROJECT_ID ${COLLECTION} ${STAGE_LOCATION} ${TEMP_LOCATION} ${WORK_BUCKET} $TEXT_PIPELINE_KEY $TEXT_PIPELINE_VERSION $AUGMENTED_TEXT_PIPELINE_KEY $AUGMENTED_TEXT_PIPELINE_VERSION $OGER_PP_PIPELINE_VERSION $CRF_PIPELINE_VERSION $ABBREV_PIPELINE_VERSION $FILTER_FLAG $JAR_VERSION $OUTPUT_PIPELINE_VERSION &> "./logs/concept-post-process-${COLLECTION}.log" &


# ---------------------------------------------
# use the below for bulk processing
#
for INDEX in $(seq 0 4 $MAX_SUBSET_INDEX)  
  do 
    ind=$(($INDEX + 0))
    if (( ind <= $MAX_SUBSET_INDEX)); then
        echo "Starting oger pipeline... ${ind} $(date)"
        COLLECTION="${SUBSET_PREFIX}${ind}"
        $SCRIPT $PROJECT_ID ${COLLECTION} ${STAGE_LOCATION} ${TEMP_LOCATION} ${WORK_BUCKET} $TEXT_PIPELINE_KEY $TEXT_PIPELINE_VERSION $AUGMENTED_TEXT_PIPELINE_KEY $AUGMENTED_TEXT_PIPELINE_VERSION $OGER_PP_PIPELINE_VERSION $CRF_PIPELINE_VERSION $ABBREV_PIPELINE_VERSION $FILTER_FLAG $JAR_VERSION $OUTPUT_PIPELINE_VERSION &> "./logs/concept-post-process-${COLLECTION}.log" &
        sleep 120
    fi
    ind=$(($INDEX + 1))
    if (( ind <= $MAX_SUBSET_INDEX)); then
        echo "Starting oger pipeline... ${ind} $(date)"
        COLLECTION="${SUBSET_PREFIX}${ind}"
        $SCRIPT $PROJECT_ID ${COLLECTION} ${STAGE_LOCATION} ${TEMP_LOCATION} ${WORK_BUCKET} $TEXT_PIPELINE_KEY $TEXT_PIPELINE_VERSION $AUGMENTED_TEXT_PIPELINE_KEY $AUGMENTED_TEXT_PIPELINE_VERSION $OGER_PP_PIPELINE_VERSION $CRF_PIPELINE_VERSION $ABBREV_PIPELINE_VERSION $FILTER_FLAG $JAR_VERSION $OUTPUT_PIPELINE_VERSION &> "./logs/concept-post-process-${COLLECTION}.log" &
        sleep 120
    fi
    ind=$(($INDEX + 2))
    if (( ind <= $MAX_SUBSET_INDEX)); then
        echo "Starting oger pipeline... ${ind} $(date)"
        COLLECTION="${SUBSET_PREFIX}${ind}"
        $SCRIPT $PROJECT_ID ${COLLECTION} ${STAGE_LOCATION} ${TEMP_LOCATION} ${WORK_BUCKET} $TEXT_PIPELINE_KEY $TEXT_PIPELINE_VERSION $AUGMENTED_TEXT_PIPELINE_KEY $AUGMENTED_TEXT_PIPELINE_VERSION $OGER_PP_PIPELINE_VERSION $CRF_PIPELINE_VERSION $ABBREV_PIPELINE_VERSION $FILTER_FLAG $JAR_VERSION $OUTPUT_PIPELINE_VERSION &> "./logs/concept-post-process-${COLLECTION}.log" &
        sleep 120
    fi
    ind=$(($INDEX + 3))
    if (( ind <= $MAX_SUBSET_INDEX)); then
        echo "Starting oger pipeline... ${ind} $(date)"
        COLLECTION="${SUBSET_PREFIX}${ind}"
        $SCRIPT $PROJECT_ID ${COLLECTION} ${STAGE_LOCATION} ${TEMP_LOCATION} ${WORK_BUCKET} $TEXT_PIPELINE_KEY $TEXT_PIPELINE_VERSION $AUGMENTED_TEXT_PIPELINE_KEY $AUGMENTED_TEXT_PIPELINE_VERSION $OGER_PP_PIPELINE_VERSION $CRF_PIPELINE_VERSION $ABBREV_PIPELINE_VERSION $FILTER_FLAG $JAR_VERSION $OUTPUT_PIPELINE_VERSION &> "./logs/concept-post-process-${COLLECTION}.log" &
    fi
    wait 
  done
