#!/usr/local/bin/bash

source ./rrun.env.sh

SCRIPT=./scripts/pipelines/collections/run_collection_assignment.sh

INPUT_DOCUMENT_CRITERIA="CRF_CRAFT|BIONLP|CRF|0.3.0;CRF_NLMDISEASE|BIONLP|CRF|0.3.0"
# INPUT_COLLECTION=PUBMED
INPUT_COLLECTION=PMCOA
TARGET_PROCESSING_STATUS_FLAG=CRF_DONE

OUTPUT_COLLECTION=REDO_2_CRF_PMOA_20231207

$SCRIPT $INPUT_DOCUMENT_CRITERIA $INPUT_COLLECTION $OUTPUT_COLLECTION $TARGET_PROCESSING_STATUS_FLAG $PROJECT_ID ${STAGE_LOCATION} ${TEMP_LOCATION} $JAR_VERSION &> "./logs/collection-assignment-${OUTPUT_COLLECTION}.log" &
