#!/bin/sh

PROJECT=$1
COLLECTION=$2
OVERWRITE=$3
REQUIRED_PROCESSING_STATUS_FLAGS=$4
INPUT_DOCUMENT_CRITERIA=$5
SENTENCE_INCLUSION_FLAG=$6
CONCEPT_DOCUMENT_TYPE=$7
ELASTICSEARCH_ADDRESSES=$8
ELASTICSEARCH_INDEX_NAME=$9
ELASTICSEARCH_API_KEY=${10}
STAGE_LOCATION=${11}
TMP_LOCATION=${12}

ZONE='us-central1-c'
REGION='us-central1'
JOB_NAME=$(echo "ELASTIC-IMPORT-${COLLECTION}" | tr '_' '-')


echo "COLLECTION: $COLLECTION"
echo "PROJECT: $PROJECT"
echo "JOB_NAME: $JOB_NAME"
echo "REQUIRED_PROCESSING_STATUS_FLAGS: $REQUIRED_PROCESSING_STATUS_FLAGS"
echo "SENTENCE_INCLUSION_FLAG: $SENTENCE_INCLUSION_FLAG"
echo "CONCEPT_DOCUMENT_TYPE: $CONCEPT_DOCUMENT_TYPE"
echo "ELASTICSEARCH_ADDRESSES: $ELASTICSEARCH_ADDRESSES"
echo "ELASTICSEARCH_INDEX_NAME: $ELASTICSEARCH_INDEX_NAME"
echo "ELASTICSEARCH_API_KEY: $ELASTICSEARCH_API_KEY"

java -Dfile.encoding=UTF-8 -jar target/tm-pipelines-bundled-0.1.0.jar ELASTICSEARCH_LOAD \
--jobName="$JOB_NAME" \
--collection="$COLLECTION" \
--overwrite="$OVERWRITE" \
--inputDocumentCriteria="$INPUT_DOCUMENT_CRITERIA" \
--requiredProcessingStatusFlags="$REQUIRED_PROCESSING_STATUS_FLAGS" \
--sentenceInclusionFlag="$SENTENCE_INCLUSION_FLAG" \
--conceptDocumentType="$CONCEPT_DOCUMENT_TYPE" \
--elasticsearchAddresses="$ELASTICSEARCH_ADDRESSES" \
--elasticsearchIndexName="$ELASTICSEARCH_INDEX_NAME" \
--elasticsearchApiKey="$ELASTICSEARCH_API_KEY" \
--project="${PROJECT}" \
--stagingLocation="$STAGE_LOCATION" \
--gcpTempLocation="$TMP_LOCATION" \
--workerZone="$ZONE" \
--region="$REGION" \
--numWorkers=10 \
--maxNumWorkers=200 \
--autoscalingAlgorithm=THROUGHPUT_BASED \
--runner=DataflowRunner