package edu.cuanschutz.ccp.tm_provider.etl.util;

public enum DocumentType {
	BIOC, TEXT, SECTIONS, DEPENDENCY_PARSE, CONCEPT_CHEBI, CONCEPT_CL, CONCEPT_GO_BP, CONCEPT_GO_CC, CONCEPT_GO_MF, CONCEPT_MOP,
	CONCEPT_NCBITAXON, CONCEPT_PR, CONCEPT_SO, CONCEPT_UBERON
}
