package edu.cuanschutz.ccp.tm_provider.etl.util;

public enum PipelineKey {
	BIOC_TO_TEXT, DEPENDENCY_PARSE, ORIG, OGER, // BERT_IDS, BERT_SPANS,
	BIGQUERY_EXPORT, FILE_LOAD, PUBANNOTATION_EXPORT, DRY_RUN, SENTENCE_SEGMENTATION, SENTENCE_COOCCURRENCE_EXPORT,
	MEDLINE_XML_TO_TEXT, CRF, SENTENCE_EXTRACTION, NORMALIZED_GOOGLE_DISTANCE_CONCEPT_KGX,
	NORMALIZED_GOOGLE_DISTANCE_CONCEPT_STORE_COUNTS, CONCEPT_POST_PROCESS, CONCEPT_ANNOTATION_EXPORT,
	WEBANNO_SENTENCE_EXTRACTION, CONCEPT_COUNT_DISTRIBUTION
}
