package edu.cuanschutz.ccp.tm_provider.etl.util;

public enum PipelineKey {
	BIOC_TO_TEXT, DEPENDENCY_PARSE, ORIG, OGER, //BERT_IDS, BERT_SPANS, 
	BIGQUERY_EXPORT, TEXT_LOAD, PUBANNOTATION_EXPORT, DRY_RUN, SENTENCE_SEGMENTATION
}
